import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author escob
 */
public class jfrmPrestamos extends javax.swing.JFrame {
  private double credito;
    private int periodoMax, periodoMin;
    private double interesMin, interesMax;
    private double incremento;

private double pagoMensual;
private boolean tablaPagos = false;

private boolean enAnios = true;

 
    
    /**
     * Creates new form jfrmPrestamos
     */
    public jfrmPrestamos() {
        initComponents();
       

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfInteresMax = new javax.swing.JTextField();
        jtfInteresMin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jbcIncremento = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtablaPrestamo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtfCcredito10 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfPeriodoMax = new javax.swing.JTextField();
        jtfPerdiodoMin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jbtCalculoAmort = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiMeses = new javax.swing.JMenuItem();
        jmiAnios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Tipo de interes ");

        jLabel6.setText("% Maximo ");

        jLabel7.setText("% Minimo");

        jLabel8.setText("Incremento");

        jbcIncremento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.5", "0.25", "1.0", "1.5", "2.0" }));
        jbcIncremento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcIncrementoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfInteresMax))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfInteresMin))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbcIncremento, 0, 102, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfInteresMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfInteresMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jbcIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jtablaPrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtablaPrestamo);

        jLabel1.setText("Credito ");

        jtfCcredito10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCcredito10ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Duracion del prestamo ");

        jLabel3.setText("Máximo");

        jLabel4.setText("Minimo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPerdiodoMin)
                            .addComponent(jtfPeriodoMax))))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtfPeriodoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfPerdiodoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Pagos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtCalculoAmort.setText("Amortizacion");
        jbtCalculoAmort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCalculoAmortActionPerformed(evt);
            }
        });

        jMenu1.setText("Prestamos en....");

        jmiMeses.setText("Meses");
        jmiMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMesesActionPerformed(evt);
            }
        });
        jMenu1.add(jmiMeses);

        jmiAnios.setText("Años");
        jmiAnios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAniosActionPerformed(evt);
            }
        });
        jMenu1.add(jmiAnios);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem3.setText("Istrucciones");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("hacerca de ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCcredito10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(jbtCalculoAmort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfCcredito10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtCalculoAmort))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCcredito10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCcredito10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCcredito10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Actualizar las variables con los valores de los controles

      try {
    double credito = Double.parseDouble(jtfCcredito10.getText());
    int periodoMin = Integer.parseInt(jtfPerdiodoMin.getText());
    int periodoMax = Integer.parseInt(jtfPeriodoMax.getText());
    double interesMin = Double.parseDouble(jtfInteresMin.getText());
    double interesMax = Double.parseDouble(jtfInteresMax.getText());
    double incremento = Double.parseDouble(jbcIncremento.getSelectedItem().toString());

    // Validaciones
    if (credito <= 0) {
        JOptionPane.showMessageDialog(this, "El crédito debe ser mayor que 0.");
        return;
    }

    if (periodoMin <= 0 || periodoMax < periodoMin) {
        JOptionPane.showMessageDialog(this, "Revise los períodos mínimo y máximo.");
        return;
    }

    if (interesMin < 0 || interesMax < interesMin) {
        JOptionPane.showMessageDialog(this, "Revise los intereses mínimo y máximo.");
        return;
    }

    if (incremento <= 0) {
        JOptionPane.showMessageDialog(this, "El incremento debe ser mayor que 0.");
        return;
    }

    // Crear el modelo de la tabla
    DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("Interés");

    // Crear las columnas de períodos
    for (int periodo = periodoMin; periodo <= periodoMax; periodo++) {

        if (enAnios) {
            modelo.addColumn(periodo + " año(s)");
        } else {
            modelo.addColumn(periodo + " mes(es)");
        }
    }

    // Calcular los pagos
    for (double interes = interesMin;
         interes <= interesMax + 0.0001;
         interes += incremento) {

        Object[] fila = new Object[periodoMax - periodoMin + 2];

        fila[0] = String.format("%.2f%%", interes);

        int columna = 1;

        for (int periodo = periodoMin;
             periodo <= periodoMax;
             periodo++) {

            int meses;

            if (enAnios) {
                meses = periodo * 12;
            } else {
                meses = periodo;
            }

            double interesMensual = interes / 100.0 / 12.0;

            double pago;

            if (interesMensual == 0) {
                pago = credito / meses;
            } else {
                pago = (credito * interesMensual)
                        / (1 - Math.pow(1 + interesMensual, -meses));
            }

            fila[columna] = String.format("%.2f", pago);

            columna++;
        }

        modelo.addRow(fila);
    }

    // Mostrar los resultados en la tabla
    jtablaPrestamo.setModel(modelo);

} catch (NumberFormatException e) {

    JOptionPane.showMessageDialog(
        this,
        "Revise que todos los datos numéricos estén escritos correctamente.",
        "Error",
        JOptionPane.ERROR_MESSAGE
    );
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jmiAniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAniosActionPerformed
        // TODO add your handling code here:
          enAnios = true;

    jmiAnios.setEnabled(false);
    jmiMeses.setEnabled(true);
    }//GEN-LAST:event_jmiAniosActionPerformed

    private void jmiMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMesesActionPerformed
        // TODO add your handling code here:
           enAnios = false;

    jmiAnios.setEnabled(true);
    jmiMeses.setEnabled(false);
    }//GEN-LAST:event_jmiMesesActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
        this,
        "INSTRUCCIONES\n\n"
        + "1. Introduzca el monto del crédito.\n"
        + "2. Indique el período mínimo y máximo.\n"
        + "3. Indique el interés mínimo y máximo.\n"
        + "4. Seleccione el incremento.\n"
        + "5. Presione el botón Pagos para realizar el cálculo.\n"
        + "6. Utilice Préstamo en → Años o Meses "
        + "para seleccionar la unidad del período.",
        "Instrucciones",
        JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
    this,
    "Aplicacion Prestamo. Version 1.0\n"
    + "Copyright (C) Luis Alejandro López Padilla",
    "",
    JOptionPane.INFORMATION_MESSAGE
);
    
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jbtCalculoAmortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalculoAmortActionPerformed
        // TODO add your handling code here:
    try {
        
        // Obtener los datos
        double monto = Double.parseDouble(jtfCcredito10.getText());
        double interesAnual = Double.parseDouble(jtfInteresMin.getText());
        int meses = Integer.parseInt(jtfPeriodoMax.getText());

        // Convertir interés anual a mensual
        double tasaMensual = (interesAnual / 100) / 12;

        // Variables
        double cuota;
        double saldo = monto;
        double totalIntereses = 0;

        // Calcular la cuota mensual
        if (tasaMensual == 0) {
            cuota = monto / meses;
        } else {
            cuota = monto *
                    (tasaMensual * Math.pow(1 + tasaMensual, meses)) /
                    (Math.pow(1 + tasaMensual, meses) - 1);
        }

        // Limpiar la tabla
        DefaultTableModel modelo =
                (DefaultTableModel) jtablaPrestamo.getModel();

        modelo.setRowCount(0);

        // Crear tabla de amortización
        for (int i = 1; i <= meses; i++) {

            double interes = saldo * tasaMensual;
            double capital = cuota - interes;

            // Evitar saldo negativo
            if (capital > saldo) {
                capital = saldo;
                cuota = capital + interes;
            }

            saldo = saldo - capital;

            totalIntereses += interes;

            // Agregar fila
            modelo.addRow(new Object[]{
                i,
                capital,
                interes,
                cuota,
                saldo
            });
        }

        JOptionPane.showMessageDialog(
                this,
                "Tabla de amortización creada.\n\n"
                + "Total de intereses: "
                + String.format("%.2f", totalIntereses)
        );

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Ingrese correctamente el monto, interés y plazo.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_jbtCalculoAmortActionPerformed

    private void jbcIncrementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcIncrementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbcIncrementoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmPrestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jbcIncremento;
    private javax.swing.JButton jbtCalculoAmort;
    private javax.swing.JMenuItem jmiAnios;
    private javax.swing.JMenuItem jmiMeses;
    private javax.swing.JTable jtablaPrestamo;
    private javax.swing.JTextField jtfCcredito10;
    private javax.swing.JTextField jtfInteresMax;
    private javax.swing.JTextField jtfInteresMin;
    private javax.swing.JTextField jtfPerdiodoMin;
    private javax.swing.JTextField jtfPeriodoMax;
    // End of variables declaration//GEN-END:variables
}
